### PR TITLE
Make it possible to enable or disable cache saving/loading per request

### PR DESCRIPTION
**Pull request by Max-Might**
Hello.

I have implemented the API as discussed in issue #15.
`cacheSave()` seems to be working fine.
Unfortunately `cacheLoad()` blocks the request for some reason.
Do you see anything obviously wrong with what I am doing?
I do not have much experience with Qt so any help would be greatly appreciated.

### CODE REVIEW

**Comment by Max-Might** [comment]
I found what the issue was.
I changed the `cacheLoad()` parameter from `CacheControl::CacheLoadControl` to `int` and it seems to be working now.

**Comment by jrbarron** [comment]
@Max-Might Great! This seems reasonable to me. Would it be too much to ask to add a unit test for this before I merge though? There is already a unit test that does some testing with caching so you can use that for inspiration. As you can see from that test case, there is a property on the `response` object called `fromCache` which indicates if the response came from the cache or not. If you can add a unit test to make sure this works as expected, then I can merge it for you. Thanks again for your contribution!

**Comment by Max-Might** [comment]
@jrbarron  I added some tests but I could not run them on my machine because my SDK setup is quite complicated.
So I fixed the travis CI file to run them.
Unfortunately the imageutils `test_scale` test fails but I don`t think it is related to my changes.

**Comment by jrbarron** [comment]
@Max-Might Sorry for the delay getting this merged, I've been really busy lately. Everything looks good to me. Great job on the auto-tests! The failing test also fails for me so most likely something changed on the services we depend on. Definitely nothing related to your code. I'll publish this as v1.5.0 shortly.

**Pull request merged**
